databases:
  - name: quiz
    databaseName: quiz
    user: quiz
    plan: free

services:
  - type: web
    name: quiz
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quiz
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false